"""Alembic environment.

Two things here are not boilerplate and are worth reading before editing.

1. The URL comes from common.session, not from alembic.ini. One env var, one place, same as
   every other process in the repo.

2. include_object filters out three kinds of database object that exist but must never
   appear in an autogenerated revision:

     * monthly partitions of raw_signals (`raw_signals_2026_07` and friends). They are
       created by a DO block in a dbmate migration and by the partition-maintenance task,
       not by a model, so autogenerate would see them as unmanaged tables and emit DROPs.
     * `daily_signal_rollup`, a materialized view. SQLAlchemy reflects it as a table it does
       not have a model for, same DROP problem.
     * `schema_migrations`, dbmate's own bookkeeping.

   The filter itself lives in common/schema_filter.py so the drift test can import the same
   rules; env.py cannot be imported by anything, because importing it runs migrations.

Coexistence with dbmate. Everything up to 2026-07-21 was applied by dbmate and stays applied
by dbmate: those files are frozen history and are still the fresh-database path. Alembic owns
everything from the baseline revision forward. Both run in order on deploy (dbmate applier
first, then `alembic upgrade head`), which is why the baseline revision is intentionally
empty. On an existing database it is a no-op; on a fresh one dbmate has already built the
schema by the time Alembic runs.
"""

from __future__ import annotations

import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import engine_from_config, pool

# packages/core is the moon project root and the parent of `common/`. Add it so this file
# imports the same way whether alembic is invoked from there or from the repo root.
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from common.models import Base  # noqa: E402
from common.schema_filter import include_object  # noqa: E402
from common.session import sqlalchemy_url  # noqa: E402

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Emit SQL to stdout instead of running it. `alembic upgrade head --sql` for review."""
    context.configure(
        url=sqlalchemy_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        include_object=include_object,
        compare_type=True,
        compare_server_default=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    section = config.get_section(config.config_ini_section, {})
    section["sqlalchemy.url"] = sqlalchemy_url()
    connectable = engine_from_config(section, prefix="sqlalchemy.", poolclass=pool.NullPool)

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
            compare_type=True,
            compare_server_default=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
